[package]
name = "luato"
version = "0.1.0"

[lib]
name = "luato"
module = "luato"
archive = "luato"

[[test]]
name = "luato-contract"
sources = ["tests/main.cpp"]

[usage]
private-definitions = [
  "LUATO_FIXTURE_DIR=\"tests/fixtures\"",
]

[[when]]
condition = 'target.os == "linux"'

[when.usage]
private-definitions = ["LUA_USE_LINUX"]

[profile]
exceptions = false
rtti = false

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[external-dependencies.cmake.lua]
find-package = "Lua"
archive = "https://www.lua.org/ftp/lua-5.5.1.tar.gz"
sha256 = "1c4b4068d67061f2a2231ad2b5422e77acea1487ea9890f6320af614f4373dce"
integration = "build-tree"
adapter = "cmake/lua.cmake"
targets = [{ name = "Lua::Lua", visibility = "public" }]
