[package]
name = "luato"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[lib]
name = "luato"
module = "luato"
archive = "luato"

[[test]]
name = "luato-contract"
sources = ["tests/main.cpp", "tests/i18n.cpp"]

[usage]
private-definitions = [
  "LUATO_FIXTURE_DIR=\"tests/fixtures\"",
]

[[when]]
condition = 'target.os == "linux"'

[when.usage]
private-definitions = ["LUA_USE_LINUX"]

[profile.base]
exceptions = false
rtti = false

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-parse]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-json]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.luato-lua]
path = "src/lua"
visibility = "public"
